# Generated by Django 4.0 on 2021-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('verify', models.BooleanField(default=False)),
                ('doc', models.CharField(choices=[('Aadhar', 'Aadhar'), ('PAN', 'PAN'), ('DL', 'DL'), ('Other', 'Other')], max_length=30)),
                ('doc_number', models.CharField(max_length=20)),
                ('flat_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('pic', models.FileField(default='avatar.png', upload_to='member')),
            ],
        ),
    ]
