# Generated by Django 4.0 on 2021-12-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0005_alter_secuser_pic'),
        ('MemberApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SecApp.secuser'),
        ),
    ]
