# Generated by Django 4.0 on 2021-12-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0005_alter_secuser_pic'),
        ('MemberApp', '0002_member_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=90)),
                ('event_des', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_at', models.DateField()),
                ('pic', models.FileField(blank=True, null=True, upload_to='Event')),
                ('interest', models.ManyToManyField(related_name='Likes', to='MemberApp.Member')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecApp.secuser')),
            ],
        ),
    ]
