# Generated by Django 4.0 on 2021-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='member', max_length=20),
        ),
    ]
