# Generated by Django 4.0 on 2022-01-18 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0007_member_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=90)),
                ('des', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solved_at', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 16, 25, 32, 930166))),
                ('complain_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member')),
            ],
        ),
    ]
