# Generated by Django 4.0 on 2022-01-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0009_complain_solve_by_alter_complain_solved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
