# Generated by Django 4.0 on 2021-12-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuser',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='Profile'),
        ),
    ]
