# Generated by Django 4.0 on 2021-12-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0002_secuser_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(choices=[('Doctor', 'Doctor'), ('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Cate', 'Cate')], max_length=50)),
                ('des', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecApp.secuser')),
            ],
        ),
    ]
