# Generated by Django 4.0 on 2021-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0004_rename_number_emergency_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuser',
            name='pic',
            field=models.FileField(default='avatar.png', upload_to='Profile'),
        ),
    ]
