# Generated by Django 4.0 on 2022-01-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuser',
            name='setting',
            field=models.BooleanField(default=False),
        ),
    ]
