# Generated by Django 4.0 on 2022-01-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0007_secuser_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
